version: '3'
services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: always
    volumes:
      - ./traccar-server-volume/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ./traccar-server-volume/logs:/opt/traccar/logs:rw
    ports:
      - "5000-5150:5000-5150"
      - "8082:8082"
    environment:
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: Traccar.110

  db:
    image: mysql:8.0.20
    container_name: db
    restart: always
    volumes:
      - ./mysql-volume/data:/var/lib/mysql
     # - ./mysql-volume/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Adnan.110
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: Traccar.110

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80


  traccar-web:
    build:
      context: ./traccar-web  # Path to your Traccar Web app source code
      dockerfile: Dockerfile
    container_name: traccar-web
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./traccar-web-volume/nginx.conf:/etc/nginx/conf.d/default.conf
